version: '3'
services:
  proxy:
    build:
      context: .
    networks:
      - site1
      - site2
    ports:
      - 80:80
    restart: always
      
networks:
  site1:
    external:
      name: site1_default
  site2:
    external:
      name: site2_default
